### ISSUE TITLE
Refactor JSONDataWriter to support better error notification

### ISSUE THREAD

**Issue by andrea-prearo** [Geek-1001/Clue#13]
**Description**

The `append` method in the `JSONWriter` class created for https://github.com/Geek-1001/Clue/issues/9 doesn't provide a straightforward way to handle errors. A nice improvements would be to either:
- Allow `JSONWriter` to throw a `JSONWriterError` as needed.
- Return a `Result<Bool, JSONWriterError>` to encapsulate the semantics of the return value(s).

Personally, I prefer using `Result`. If we go down this path, we have two possible scenarios:
- We create our own simple `Result` type (with limited functionality):
```
enum Result<T, ErrorType> {
  case success(T)
  case error(ErrorType)
}
```
- We take advantage of the existing [Result](https://github.com/antitypical/Result) library, which provides a lot of useful additional functionality. This would require introducing third-party Cocoapod dependencies (with the related pros and cons).

All the suggested above enhancements are not compatible with Objective-C code. In order to start working on these improvements, we first need to migrate all writing functionality related classes to Swift.

**Depends on https://github.com/Geek-1001/Clue/issues/11 and https://github.com/Geek-1001/Clue/issues/12.**

**Comment by Geek-1001** [comment]
Hi @andrea-prearo 
Got it. Make sense.

>We create our own simple `Result` type (with limited functionality):

I like the `Result` approach as well. I don't think it's necessary to import third-party library for that. 
We can create our small implementation of `Result` at least for now.
